export {
  CIR_SCHEMA_VERSION,
  CirNodeSchema,
  DiagnosticSchema,
  IgnoredDiagnosticSchema,
  LEXICON_TRANSFORM_VERSION,
  LexiconEntryAuthoringCollectionSchema,
  LexiconEntryAuthoringSchema,
  LexiconEntrySchema,
  LexiconEntryTypeSchema,
  LexiconMatchAuditSchema,
  LexiconScopeSchema,
  ParagraphBreakNodeSchema,
  ParseScriptInputSchema,
  ParseScriptResultSchema,
  PauseNodeSchema,
  PronunciationAnnotationSchema,
  PronunciationDiscoverySchema,
  SCRIPT_GRAMMAR_VERSION,
  SectionNodeSchema,
  SourcePositionSchema,
  SourceRangeSchema,
  SpeakerIdSchema,
  SpeechNodeSchema,
  SYSTEM_DEFAULT_SPEAKER_ID,
  TransformDiagnosticSchema,
  TransformScriptInputSchema,
  TransformScriptResultSchema,
  TransformedSpeechSegmentSchema,
  type CirNode,
  type IgnoredDiagnostic,
  type LexiconEntryAuthoring,
  type LexiconEntryAuthoringCollection,
  type LexiconEntry,
  type LexiconMatchAudit,
  type ParseDiagnostic,
  type ParseScriptInput,
  type ParseScriptResult,
  type PronunciationAnnotation,
  type SourceRange,
  type TransformDiagnostic,
  type TransformScriptInput,
  type TransformScriptResult,
  type TransformedSpeechSegment
} from "./schemas.js";
export { parseScript } from "./parser.js";
export {
  normalizeLexiconEntries,
  type NormalizeLexiconEntriesOptions,
  type NormalizeLexiconEntriesResult
} from "./lexicon.js";
export { transformScript } from "./transformer.js";
