export {
  CIR_SCHEMA_VERSION,
  CirNodeSchema,
  DiagnosticSchema,
  DEFAULT_PARAGRAPH_PAUSE_DURATION_MS,
  DEFAULT_PARAGRAPH_PAUSE_ID,
  IgnoredDiagnosticSchema,
  LEXICON_TRANSFORM_VERSION,
  LexiconEntryAuthoringCollectionSchema,
  LexiconEntryAuthoringSchema,
  LexiconEntrySchema,
  LexiconEntryTypeSchema,
  LexiconMatchAuditSchema,
  LexiconScopeSchema,
  ParagraphBreakNodeSchema,
  ParagraphPauseConfigurationSchema,
  PARAGRAPH_PACING_VERSION,
  ParseScriptInputSchema,
  ParseScriptResultSchema,
  PauseNodeSchema,
  PauseIdSchema,
  PronunciationAnnotationSchema,
  PronunciationDiscoverySchema,
  ResolveParagraphPausesInputSchema,
  ResolveParagraphPausesResultSchema,
  ResolvedParagraphPauseAuditSchema,
  SCRIPT_GRAMMAR_VERSION,
  SectionNodeSchema,
  SourcePositionSchema,
  SourceRangeSchema,
  SpeakerIdSchema,
  SpeechNodeSchema,
  SYSTEM_DEFAULT_SPEAKER_ID,
  TransformDiagnosticSchema,
  TransformScriptInputSchema,
  TransformScriptResultSchema,
  TransformedSpeechSegmentSchema,
  type CirNode,
  type IgnoredDiagnostic,
  type LexiconEntryAuthoring,
  type LexiconEntryAuthoringCollection,
  type LexiconEntry,
  type LexiconMatchAudit,
  type ParseDiagnostic,
  type ParseScriptInput,
  type ParseScriptResult,
  type ParagraphPauseConfiguration,
  type PronunciationAnnotation,
  type ResolveParagraphPausesInput,
  type ResolveParagraphPausesResult,
  type ResolvedParagraphPauseAudit,
  type SourceRange,
  type TransformDiagnostic,
  type TransformScriptInput,
  type TransformScriptResult,
  type TransformedSpeechSegment
} from "./schemas.js";
export { parseScript } from "./parser.js";
export {
  normalizeLexiconEntries,
  type NormalizeLexiconEntriesOptions,
  type NormalizeLexiconEntriesResult
} from "./lexicon.js";
export { transformScript } from "./transformer.js";
export { resolveParagraphPauses } from "./pacing.js";
